server:
  port: 8004
spring:
  application:
    name: eureka-security-server
  security: #配置SpringSecurity登录用户名和密码
    user:
      name: macro
      password: 123456
  profiles:
    active: dev
eureka:
  environment: dev
  datacenter: Eureka Server
  instance:
    hostname: localhost

  client:
    fetch-registry: false
    register-with-eureka: false
